#############################
game:

  scale:  20
  width:  300
  height: 300
  fps: 10

#############################
model:

  lambda: 0.95
  gamma: 0.95 #0.99
  epsilon: 0.2

  learning_rate: 0.0003
  hidden_units: 256

  trajectory_length: 3
  batch_size: 5

  n_epochs: 4
#############################
training:
  episodes: 10000000
#############################
eval:
  episodes: 100
#############################
env:
  name: "tron" # tron, ...
  render_mode: # "human" , <nothing> 
  cnn: True
#############################
